import HTSeq
from scipy.stats import poisson
from time import time

from price2.reference_annotation import ReferenceAnnotation
from price2.genomic_features import ReadGeneratingRegion
from price2.ribo_seq_alignment import RiboSeqAlignment
from price2.cleavage_model import CleavageModel
from price2.rgr_finder import RGRFinder
from price2.locus import Locus

#class CompatibilityGroup:
#    def __init__(self, length: int=0) -> None:
#        self.length = length
#        self.read_count = 0
#
#
#class AssociationGroup:
#    def __init__(self) -> None:
#        self.read_count = 0


#class Locus:
#    interval: HTSeq.GenomicInterval
#    association_groups: dict[(frozenset[(str, int), int, bool]): AssociationGroup]
#    compatibility_groups: dict[frozenset[str]: CompatibilityGroup]
#    read_count: int
#    read_generating_regions: set[ReadGeneratingRegion]
#    rrc: dict # for plotting
#    lls: dict # for plotting
#
#    def __init__(self, interval: HTSeq.GenomicInterval) -> None:
#        self.interval = interval
#        self.read_count = 0
#        self.read_generating_regions = set()
#        self.active_regions = set()
#        self.rrc = {} # for plotting
#        self.region_activities = {} # for plotting
#        self.lls = [] # for plotting
#        self.activity_changes = [] # for plotting
#
#    
#    def __len__(self) -> int:
#        return self.interval.length
#    
#
#    def make_compatibility_groups(self, rgr_finder: RGRFinder) -> None:
#        rgr_intervals = rgr_finder.rgr_intervals[self.interval]
#        self.compatibility_groups = {}
#        
#        self.regions = set()
#        iv = self.interval
#        for step_iv, step_set in rgr_intervals[iv].steps():
#            self.regions |= step_set
#            fr_set  = frozenset(step_set)
#            if not fr_set:
#                continue # ignore empty regions
#            if not fr_set in self.compatibility_groups:
#                cg = CompatibilityGroup()
#                self.compatibility_groups[fr_set] = cg
#            self.compatibility_groups[fr_set].length += step_iv.length
#
#
#
#    def add_alignment(self, alignment: RiboSeqAlignment) -> None:
#        # compute association group
#        length = alignment.matching_length
#        oua = alignment.untemplated_addition
#        region_frame = set()
#
#        
#
#
#    def run_orf_deconvolution(self,
#                              iterations: int,
#                              likelihood_cutoff: float,
#                              cleavage_model: CleavageModel,
#                              ) -> None:
#        if self.read_count < 5: return
#        
#        start_time = time()
#
#        self.active_regions = self.regions.copy()
#
#        for region in self.regions:
#            self.region_activities[region] = []
#            self.rrc[region] = []
#
#        for i in range(iterations):
#            for region in self.active_regions:
#                region.read_count = 0
#            
#            # E-step (assign reads to regions)
#            for (region_frame, length, oua), ag in self.association_groups.items():
#                count = ag.read_count
#                likelihoods = {}
#
#                # compute the likelihood for a read in this association group to be generated by each overlapping region
#                for region, frame in region_frame:
#                    likelihoods[region] = cleavage_model.pmf(length, oua, frame) * region.activity
#
#                # normalize likelihoods and assign read counts to regions
#                likelihood_sum = sum(likelihoods.values())
#                p = {region: likelihoods[region]/likelihood_sum for region in likelihoods}
#                for region, frame in region_frame:
#                    region.read_count += count * p[region]
#
#            # M-step (update region activities)
#            for region in self.active_regions:
#                region.activity = region.read_count / len(region) # region.read_fraction = region.read_count / self.read_count
#    
#            self.lls.append(self.incomplete_data_likelihood())
#
#            for region in self.regions:
#                self.region_activities[region].append(region.activity)
#            for region in self.active_regions:
#                self.rrc[region].append(region.read_count)
#
#            # sum differences in region activities
#            if i>1:
#                activity_change = 0
#                for region in self.regions:
#                    activity_change += abs(self.region_activities[region][-1] - self.region_activities[region][-2])
#                self.activity_changes.append(activity_change)
#                # regularize if activity changes less than delta_cutoff, if this does not work break
#                if activity_change < likelihood_cutoff:
#                    if not self.regularize(likelihood_cutoff, cleavage_model):
#                        #print('break at iteration', i)
#                        self.break_iteration = i
#                        end_time = time()
#                        self.runtime = end_time - start_time
#                        break
#        self.break_iteration = iterations
#        end_time = time()
#        self.runtime = end_time - start_time
#
#    
#    # the incomplete data likelihood as defined in the lecture
#    # product of likelihoods of all compatibility groups (expected read count vs actual read count assuming poisson distribution)
#    def incomplete_data_likelihood(self) -> float:
#        ll = 0
#        for cg_regions, cg in self.compatibility_groups.items():
#            activity = sum([region.activity for region in cg_regions])
#            expected_reads_in_cg = cg.length * activity
#            actual_reads_in_cg = cg.read_count
#            ll += poisson.logpmf(actual_reads_in_cg, expected_reads_in_cg)
#        return ll
#    
#
#    def regularize(self, likelihood_cutoff: float, cleavage_model) -> bool:
#        success = False
#        ll = self.incomplete_data_likelihood()
#        regularized_regions = []
#        for region in self.active_regions:
#            region.original_activity = region.activity
#        for rem_region in self.active_regions:
#            # experimentally remove region, reassign reads and compute new likelihood
#            for region in self.active_regions:
#                region.read_count = 0
#
#            # E-step
#            con = False
#            for (region_frame, length, oua), ag in self.association_groups.items():
#                count = ag.read_count
#                likelihoods = {}
#
#                for region, frame in region_frame:
#                    if region == rem_region:
#                        likelihoods[region] = 0
#                    else:
#                        likelihoods[region] = cleavage_model.pmf(length, oua, frame) * region.activity
#                
#                likelihood_sum = sum(likelihoods.values())
#                if likelihood_sum == 0:
#                    con = True
#                    break
#                p = {region: likelihoods[region]/likelihood_sum for region in likelihoods}
#                for region, frame in region_frame:
#                    region.read_count += count * p[region]
#
#            if con:
#                continue
#
#            # M-step
#            for region in self.active_regions:
#                region.activity = region.read_count / len(region)
#
#            if self.incomplete_data_likelihood() + likelihood_cutoff > ll:
#                success = True
#                regularized_regions.append(rem_region)
#
#            for region in self.active_regions:
#                region.activity = region.original_activity
#
#        for region in regularized_regions:
#            self.deactivate_region(region, inplace=True)
#
#        return success
#    
#
#    def deactivate_region(self, rem_reg: ReadGeneratingRegion, inplace: bool=True) -> None:
#        active_regions = set([region for region in self.active_regions if region != rem_reg])
#        if inplace:
#            self.active_regions = active_regions
#            rem_reg.activity = 0


class ORFActivityEstimator:

    def __init__(
            self,
            cm: CleavageModel,
            reference_annotation: ReferenceAnnotation,
            rgr_finder: RGRFinder,
            read_alignment_file_path: str,
            overlap_likelihood_ratio_threshold: float = .99,
            delta_cutoff: float=1,
            maxiter: int=100,
            ) -> None:
        self.cm = cm
        self.reference_annotation = reference_annotation
        self.rgr_finder = rgr_finder
        self.bam_file = HTSeq.BAM_Reader(read_alignment_file_path)
        self.overlap_likelihood_ratio_threshold = overlap_likelihood_ratio_threshold
        self.delta_cutoff = delta_cutoff
        self.maxiter = maxiter
        #self.make_loci()
        #self.make_compatibility_groups()


    def run_orf_deconvolution(self) -> None:
        current_loci = {'+': None, '-': None}
        for alignment in self.bam_file:
            if alignment.attributes['NH'] != 1:
                continue
            alignment = RiboSeqAlignment(alignment)
            if alignment.matching_length < 15 or alignment.matching_length > 40:
                continue

            if current_loci[alignment.genomic_region.strand] and \
                alignment.alignment.iv.start > current_loci[alignment.genomic_region.strand].interval.end:
                current_loci[alignment.genomic_region.strand].run_orf_deconvolution()
                self.finished_loci.append(current_loci[alignment.genomic_region.strand])
                current_loci[alignment.genomic_region.strand] = None
            
            if not current_loci[alignment.genomic_region.strand]:
                current_loci[alignment.genomic_region.strand] = self.get_locus(alignment)
                if not current_loci[alignment.genomic_region.strand]:
                    continue
            current_loci[alignment.genomic_region.strand].add_alignment(alignment)
        if current_loci['+']:
            current_loci['+'].run_orf_deconvolution()
        if current_loci['-']:
            current_loci['-'].run_orf_deconvolution()
            


    def make_loci(self) -> None:
        loci_intervals_binary = HTSeq.GenomicArray("auto", stranded=True, storage="step", typecode='b')
        for transcript in self.reference_annotation.transcripts.values():
            loci_intervals_binary[transcript.iv] = True
        self.loci_intervals = HTSeq.GenomicArray("auto", stranded=True, storage="step", typecode='O')
        self.loci_set = set()
        for iv, step in loci_intervals_binary.steps():
            if step:
                locus = Locus(iv, self.cm)
                self.loci_intervals[iv] = locus
                #self.loci_set.add(locus)


    def get_locus(self, alignment: RiboSeqAlignment) -> Locus:
        #for iv in alignment.genomic_region.intervals:
        #    if tmp:=self.loci_intervals[iv]:
        #        return tmp
        #return None 

        for iv in alignment.genomic_region.intervals:
            loci = set()
            for step in self.loci_intervals[iv].steps():
                loci |= step[1]
            if len(loci) == 1:
                tmp = loci.pop()
                print(type(tmp))
                return loci.pop()
            elif len(loci) == 0:
                return None
            else:
                raise ValueError("Multiple loci found for alignment.")       


    def make_compatibility_groups(self) -> None:
        rgr_intervals = self.rgr_finder.rgr_intervals
        self.compatibility_groups = {}
        for locus in self.loci_set:
            locus.regions = set()
            iv = locus.interval
            for step_iv, step_set in rgr_intervals[iv].steps():
                locus.regions |= step_set
                fr_set  = frozenset(step_set)
                if not fr_set:
                    continue # ignore empty regions
                if not fr_set in self.compatibility_groups:
                    cg = CompatibilityGroup()
                    self.compatibility_groups[fr_set] = cg
                    locus.compatibility_groups[fr_set] = cg
                locus.compatibility_groups[fr_set].length += step_iv.length

    
    def fill_groups(self) -> None:
        
        self.association_groups = {}

        for read_al in self.bam_file:
            read_al = RiboSeqAlignment(read_al)
            if read_al.matching_length < 15 or read_al.matching_length > 40:
                continue
            if not read_al.unique:
                continue
            try:
                locus = self.get_locus(read_al)
            except ValueError:
                continue
            # compute association group
            length = read_al.matching_length
            oua = read_al.untemplated_addition
            region_frame = set()

            candidate_regions = self.rgr_finder.collect_rgrs(read_al.genomic_region)
            
            if len(candidate_regions) == 1:
                region = candidate_regions.pop()
                try:
                    iv_on_region = region.genomic_region.induce(read_al.genomic_region)
                except ValueError:
                    continue
                if region.type == 'ORF':
                    frame = iv_on_region[0]%3
                else:
                    frame = None
                region_frame.add((region, frame))
            
            else:
                for region in candidate_regions:
                    try:
                        iv_on_region = region.genomic_region.induce(read_al.genomic_region)
                    except ValueError:
                        continue
                    if region.type == 'ORF':
                        frame = iv_on_region[0]%3
                    else:
                        frame = None
                    complete_likelihood = self.cm.pmf(
                        length, 
                        oua,
                        frame,
                    )
                    if iv_on_region[0] < 0 or iv_on_region[1] > len(region.genomic_region):
                        overlap_likelihood = self.cm.pmf(
                            length, 
                            read_al.untemplated_addition, 
                            frame, 
                            region_start = -iv_on_region[0],
                            region_end = -iv_on_region[0] + len(region.genomic_region),
                            )
                        try:
                            if overlap_likelihood/complete_likelihood >= self.overlap_likelihood_ratio_threshold:
                                region_frame.add((region, frame))
                        except ZeroDivisionError:
                            continue
                    else:
                        region_frame.add((region, frame))

            region_frame = frozenset(region_frame)
            
            if not (region_frame, length, oua) in self.association_groups:
                ag = AssociationGroup()
                self.association_groups[(region_frame, length, oua)] = ag
                locus.association_groups[(region_frame, length, oua)] = ag
            self.association_groups[(region_frame, length, oua)].read_count += 1
            locus.read_count += 1

        for locus in self.loci_set:
            for ag in locus.association_groups:
                regions = {x[0] for x in ag[0]}
                regions = frozenset(regions)
                if not regions in self.compatibility_groups:
                    cg = CompatibilityGroup(length=1)
                    self.compatibility_groups[regions] = cg
                    locus.compatibility_groups[regions] = cg
                self.compatibility_groups[regions].read_count += self.association_groups[ag].read_count

        self.total_read_count = sum([ag.read_count for ag in self.association_groups.values()])
        
        for locus in self.loci_set:
            locus.rrc = {}
            for region in locus.regions:
                region.activity = locus.read_count / len(locus)
                locus.rrc[region] = []

    #def get_locus(self, ribo_seq_alignment: RiboSeqAlignment) -> Locus:
    #    loci = set()
    #    for iv in ribo_seq_alignment.genomic_region.intervals:
    #        for step in self.loci_intervals[iv].steps():
    #            if step[1]:
    #                loci.add(step[1])
    #    if len(loci) > 1:
    #        raise ValueError('Alignment overlaps multiple loci')
    #    if len(loci) == 0:
    #        raise ValueError('Alignment overlaps no locus')
    #    return loci.pop()
    
